name: update-homebrew-tap

on:
  release:
    types: [published]

permissions:
  contents: read
  pull-requests: write

jobs:
  update-tap:
    name: Update Homebrew tap formula
    runs-on: ubuntu-latest
    env:
      TAP_TOKEN: ${{ secrets.TAP_TOKEN }}
    steps:
      - name: Check token
        id: check
        run: |
          if [ -z "${TAP_TOKEN}" ]; then
            echo "has_token=false" >> "$GITHUB_OUTPUT"
          else
            echo "has_token=true" >> "$GITHUB_OUTPUT"
          fi
      - name: Compute URL and SHA256
        id: meta
        if: steps.check.outputs.has_token == 'true'
        run: |
          set -euo pipefail
          TAG='${{ github.event.release.tag_name }}'
          REPO='${{ github.repository }}'
          URL="https://github.com/${REPO}/archive/refs/tags/${TAG}.tar.gz"
          TMP=$(mktemp)
          curl -fsSL "$URL" -o "$TMP"
          if command -v sha256sum >/dev/null 2>&1; then
            SHA=$(sha256sum "$TMP" | awk '{print $1}')
          else
            SHA=$(shasum -a 256 "$TMP" | awk '{print $1}')
          fi
          echo "url=$URL" >> "$GITHUB_OUTPUT"
          echo "sha=$SHA" >> "$GITHUB_OUTPUT"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
          echo "version=${TAG#v}" >> "$GITHUB_OUTPUT"

      - name: Checkout tap repository
        uses: actions/checkout@v4
        if: steps.check.outputs.has_token == 'true'
        with:
          repository: rhukster/homebrew-tap
          token: ${{ secrets.TAP_TOKEN }}
          path: tap

      - name: Update formula file
        working-directory: tap
        if: steps.check.outputs.has_token == 'true'
        env:
          URL: ${{ steps.meta.outputs.url }}
          SHA: ${{ steps.meta.outputs.sha }}
        run: |
          set -euo pipefail
          F="Formula/find-symlinks.rb"
          test -f "$F"
          sed -i -E "s|^\\s*url\\s+\"[^\"]+\"|  url \"${URL}\"|g" "$F"
          sed -i -E "s|^\\s*sha256\\s+\"[^\"]+\"|  sha256 \"${SHA}\"|g" "$F"
          echo "Updated formula:" && git --no-pager diff -- "$F" || true

      - name: Commit and push to tap
        if: steps.check.outputs.has_token == 'true'
        working-directory: tap
        env:
          TAG: ${{ steps.meta.outputs.tag }}
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if git diff --quiet -- Formula/find-symlinks.rb; then
            echo "No changes in formula; nothing to commit."
            exit 0
          fi
          git add Formula/find-symlinks.rb
          git commit -m "find-symlinks: update to ${TAG}"
          git push origin HEAD:main

      - name: Skip (TAP_TOKEN not set)
        if: steps.check.outputs.has_token != 'true'
        run: |
          echo "TAP_TOKEN not set; skipping tap update. Add a repo secret named TAP_TOKEN with a PAT that has repo scope."
